'use strict';

var quoteList = [
  { quote: 'He is able who thinks he is able.',
  cite: 'Buddha' },
  { quote: 'If you believe it will work out, you’ll see opportunities. If you believe it won’t, you will see obstacles.',
  cite: 'Wayne Dyer' },
  { quote: 'The journey is the reward.',
  cite: 'Chinese Proverb' },
  { quote: 'Time is the most valuable thing a man can spend.',
  cite: 'Theophrastus' },
  { quote: 'Life is what happens while you are making other plans.',
  cite: 'John Lennon' },
  { quote: 'Life is like riding a bicycle. To keep your balance you must keep moving.',
  cite: 'Einstein' },
  { quote: 'Better to do something imperfectly than to do nothing flawlessly.',
  cite: 'Robert H. Schuller' },
  { quote: 'If you crawl in the right direction, you will get there faster than if you run in the wrong direction.',
  cite: 'Unknown' },
  { quote: 'If you get up one more time than you fall, you will make it through.',
  cite: 'Chinese Proverb' },
  { quote: 'No man is a failure who is enjoying life.',
  cite: 'William Faulkner' },
  { quote: 'Happiness is not a goal…it’s a by-product of a life well lived.',
  cite: 'Eleanor Roosevelt' },
  { quote: 'What you get by achieving your goals is not as important as what you become by achieving your goals.',
  cite: 'Johann Wolfgang von Goethe' },
  { quote: 'A year from now you may wish you had started today.',
  cite: 'Karen Lamb' },
  { quote: 'Life isn’t about waiting for the storm to pass. It’s about learning how to dance in the rain.',
  cite: 'Vivian Greene' },
  { quote: 'If the path before you is clear, you’re probably on someone else’s.',
  cite: 'Joseph Campbell' },
  { quote: 'Don’t use a lot where a little will do.',
  cite:'Proverb' },
  { quote: 'A year from now you may wish you had started today.',
  cite: 'Karen Lamb' },
  { quote: 'What you do today can improve all your tomorrows.',
    cite: 'Ralph Marston' },
  { quote: 'Don’t put off for tomorrow what you can do today because if you enjoy it today, you can do it again tomorrow.',
  cite: 'James A. Michener' },
  { quote: 'Don’t wait for your feelings to change to take the action. Take the action and your feelings will change.',
  cite: 'Barbara Baron' },
  { quote: 'If it is important to you, you will find a way. If not, you’ll find an excuse.',
  cite: 'Unknown' },
  { quote: 'The future is always beginning now.',
  cite: 'Mark Strand' },
  { quote: 'What you do today is important, because you are exchanging a day of your life for it.',
  cite: 'Unknown' },
  { quote: 'Time is the most valuable thing a man can spend.',
  cite: 'Theophrastus' },
  { quote: 'Don’t count every hour in the day, make every hour in the day count.',
  cite: 'Unknown' },
  { quote: 'A good plan today is better than a perfect plan tomorrow.',
  cite: 'Proverb' },
  { quote: 'If you do what you always did, you will get what you always got.',
  cite: 'Albert Einstein' },
  { quote: 'We can always choose to perceive things differently. We can focus on what’s wrong in our life, or we can focus on what’s right.',
  cite: 'Marianne Williamson' }
];
